name: Build Executable

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Build Executable with PyInstaller
        run: |
          pyinstaller main.spec
      
      - uses: actions/upload-artifact@v4
        with:
          name: VCardToQRCode
          path: dist/VCardToQRCode.exe
        
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
        
      - name: Bundle Release
        id: bundle-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.date.outputs.date }}_${{ github.run_id }}
          release_name: Release ${{ steps.date.outputs.date }}
          body: |
            ## Changes in this release
            - See commit ${{ github.event.head_commit.id }} for details.
          draft: false
          prerelease: false
        
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.bundle-release.outputs.upload_url }}
          asset_path: ./dist/VCardToQRCode.exe
          asset_name: VCardToQRCode.exe
          asset_content_type: application/zip